version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_backend_simr #Ganti nama bro sesuai selera
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
